#!/usr/bin/env python3
"""RUBP codec conformance for the Dragon 32 client.

Runs the real client codec from ../src/rubp.asm on a real Dragon 32 under
Emu198x (emu198x-dragon, headless) and checks it against the golden fixtures in
rubp-messages-v1.json — the same vectors the iOS reference and the Go server
validate against. No networking, no running game.

Two phases:

  Encoders — drive HELLO / PLAY_CARD / DRAW_CARD with the fixture's field values
    and diff the 64-byte message each builds against its golden vector. Differing
    bytes are classified OK-NAME / OK-PLATFORM / GAP / BUG / UNEXPECTED.

  Decoders — feed the golden WELCOME / GAME_STATE vectors into the parsers and
    check each extracted value against the same vector decoded at the spec's
    offsets (an independent oracle: a parser reading the wrong offset fails).

The harness is a Dragon cartridge. Once BASIC boots, the cartridge autostart
FIRQ jumps to it; it runs every test into a RAM capture region and parks, and
memory_read pulls each region back.

Exit status is non-zero on any BUG / UNEXPECTED / decoder mismatch.

Usage:  python3 run.py
Needs: lwasm (lwtools), emu198x-dragon (set EMU198X_DRAGON, or it defaults to
       ~/Projects/198x/Emu198x/target/debug/emu198x-dragon), and the Dragon 32
       BASIC ROM (set EMU198X_DRAGON_ROM, or it defaults to
       ~/Projects/198x/Emu198x/roms/dragon/dragon32.rom).
"""
import hashlib
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BUILD = os.path.join(HERE, "build")
FIXTURES = os.path.join(HERE, "rubp-messages-v1.json")
FIXTURES_SHA = os.path.join(HERE, "rubp-messages-v1.sha256")
ROM = os.path.join(BUILD, "harness.rom")
RAM_DUMP = os.path.join(BUILD, "ram.bin")
# Bus cycles to run: enough for BASIC to cold-boot (~0.9 MHz) and the cartridge
# autostart FIRQ to fire and run the harness, which then parks.
CYCLES = 4_000_000
EMU = os.environ.get(
    "EMU198X_DRAGON",
    os.path.expanduser("~/Projects/198x/Emu198x/target/debug/emu198x-dragon"),
)
BASIC_ROM = os.environ.get(
    "EMU198X_DRAGON_ROM",
    os.path.expanduser("~/Projects/198x/Emu198x/roms/dragon/dragon32.rom"),
)

# Capture addresses — must match harness.asm.
ENC_SLOTS = {"hello": 0x6800, "play_card": 0x6840, "draw_card": 0x6880}
DEC_SLOTS = {"welcome": (0x68C0, 6), "game_state": (0x68D0, 25)}
DONE = 0x68FF
CONN_WAITING = 2  # parse_welcome sets this (CONN_WAITING in equates.asm)

# Per-message, per-offset explanations for known differences from the golden
# vectors. Anything that differs and is NOT listed here is reported UNEXPECTED.
KNOWN = {
    "hello": {
        # The player name is user data; the client sends its own ("DRAGON").
        **{o: ("OK-NAME", "player name vs fixture's 'Alice' (user data)") for o in range(16, 32)},
        33: ("OK-PLATFORM", "platform ID 0x00A0 (Dragon) vs fixture's 0x0031 (iOS)"),
        # specVersion (34/35) is now emitted; reconnectToken stays a gap (no reclaim).
        **{o: ("GAP", "reconnectToken not emitted (no reconnect support)") for o in range(36, 44)},
    },
    "play_card": {},
    "draw_card": {},
}
FAIL_STATUSES = {"BUG", "UNEXPECTED"}


def golden(fixtures, name):
    for m in fixtures["messages"]:
        if m["name"] == name:
            return bytes.fromhex(m["hex"])
    raise KeyError(name)


def emit_byte_table(label, data):
    lines = [label]
    for i in range(0, len(data), 16):
        lines.append("        fcb     " + ",".join(f"${b:02x}" for b in data[i:i + 16]))
    return "\n".join(lines)


def gen_vectors_inc(fixtures):
    os.makedirs(BUILD, exist_ok=True)
    body = [
        "; Generated by run.py from rubp-messages-v1.json — do not edit.",
        emit_byte_table("welcome_msg", golden(fixtures, "welcome")),
        emit_byte_table("game_state_msg", golden(fixtures, "game_state")),
        "",
    ]
    with open(os.path.join(BUILD, "vectors.inc"), "w") as f:
        f.write("\n".join(body))


# A Dragon cartridge only autostarts reliably at a standard ROM size — odd
# sizes (the raw harness is ~1 KB) leave the cartridge window mis-mapped and the
# autostart FIRQ never lands on $C000. Pad the image up to a real 4 KB cart.
CART_SIZE = 4096


def assemble():
    subprocess.run(["lwasm", "--raw", "-o", ROM, "harness.asm"], cwd=HERE, check=True)
    with open(ROM, "rb") as f:
        image = f.read()
    if len(image) > CART_SIZE:
        sys.exit(f"harness ROM is {len(image)} bytes, larger than the {CART_SIZE}-byte cart window")
    with open(ROM, "wb") as f:
        f.write(image + b"\xff" * (CART_SIZE - len(image)))


def capture():
    """Boot BASIC with the harness cartridge, then read the RAM capture region.

    emu198x-dragon's headless mode runs N bus cycles and dumps the full 32 KiB
    RAM image; there is no scripted memory_read. BASIC cold-boots, the cartridge
    autostart FIRQ jumps to the harness, it runs every test into the capture
    region and parks, and we slice the regions straight out of the RAM dump.
    """
    if not os.path.exists(EMU):
        sys.exit(f"emu198x-dragon not found at {EMU}\n"
                 f"build it: cargo build -p emu198x-dragon --no-default-features")
    if not os.path.exists(BASIC_ROM):
        sys.exit(f"Dragon 32 BASIC ROM not found at {BASIC_ROM}\n"
                 f"set EMU198X_DRAGON_ROM to its path")
    subprocess.run(
        [EMU, "--headless", "--rom", BASIC_ROM, "--cart", ROM,
         "--cycles", str(CYCLES), "--dump-ram", RAM_DUMP],
        cwd=HERE, check=True, capture_output=True, text=True,
    )
    with open(RAM_DUMP, "rb") as f:
        ram = f.read()
    if ram[DONE] != 0xAA:
        raise RuntimeError("harness did not finish (done marker not set) — "
                           "BASIC may need more cycles to boot and autostart the cartridge")
    got = {a: ram[a:a + 64] for a in ENC_SLOTS.values()}
    for addr, length in DEC_SLOTS.values():
        got[addr] = ram[addr:addr + length]
    return got


def u16be(b, off):
    return (b[off] << 8) | b[off + 1]


def check_encoders(fixtures, got):
    print("ENCODERS — message the client builds vs golden vector\n")
    failed = False
    for name, addr in ENC_SLOTS.items():
        produced, gold = got[addr], golden(fixtures, name)
        known = KNOWN.get(name, {})
        diffs = [i for i in range(64) if produced[i] != gold[i]]
        statuses = [(i, *known.get(i, ("UNEXPECTED", "no explanation on file"))) for i in diffs]
        bug = any(s in FAIL_STATUSES for _, s, _ in statuses)
        failed = failed or bug
        verdict = "CONFORMANT" if not diffs else ("FAIL" if bug else "conformant (documented gaps only)")
        print(f"== {name:<10} {verdict} ==")
        if not diffs:
            print("   byte-for-byte match\n")
            continue
        for i, status, note in statuses:
            print(f"   @{i:2d}  DRAGON={produced[i]:02x} golden={gold[i]:02x}  [{status}] {note}")
        print()
    return failed


def check_decoders(fixtures, got):
    w = golden(fixtures, "welcome")
    wp = w[16:]
    wc = got[DEC_SLOTS["welcome"][0]]
    welcome_checks = [
        ("assignedPlayerID",  wc[0] | (wc[1] << 8), u16be(wp, 0)),
        ("gameID",            wc[2] | (wc[3] << 8), u16be(wp, 2)),
        ("playerCount",       wc[4],                wp[4]),
        ("connState=WAITING", wc[5],                CONN_WAITING),
    ]

    g = golden(fixtures, "game_state")
    gp = g[16:]
    gc = got[DEC_SLOTS["game_state"][0]]
    gs_checks = [
        ("currentPlayer", gc[0], gp[0]),
        ("direction",     gc[1], gp[1]),
        ("topCard",       gc[2], gp[2]),
        ("nominatedSuit", gc[3], gp[3]),
        ("pendingDraws",  gc[4], gp[4]),
        ("deckCount",     gc[5], gp[6]),
    ]
    for i in range(8):
        gs_checks.append((f"playerCount[{i}]", gc[6 + i], gp[7 + i]))
    gs_checks += [
        ("isGameOver",  gc[14], gp[15]),
        ("winnerIndex", gc[15], gp[16]),
    ]
    for i in range(8):
        gs_checks.append((f"stateHash[{i}]", gc[16 + i], gp[24 + i]))
    gs_checks.append(("hashValid", gc[24], 1 if (gp[23] & 0x01) else 0))

    print("DECODERS — value the parser extracted vs golden vector at spec offsets\n")
    failed = False
    for name, checks in [("welcome", welcome_checks), ("game_state", gs_checks)]:
        bad = [(label, got_v, want_v) for label, got_v, want_v in checks if got_v != want_v]
        failed = failed or bool(bad)
        print(f"== {name:<10} {'PASS' if not bad else 'FAIL'} ==")
        if bad:
            for label, got_v, want_v in bad:
                print(f"   {label:<18} got={got_v:#04x} want={want_v:#04x}")
        else:
            print(f"   all {len(checks)} fields extracted correctly")
        print()
    return failed


def check_fixtures_pinned():
    """Refuse to run against vectors that no longer match the ones we pinned.

    The vectors are vendored rather than fetched, because this harness runs
    offline by design and a fresh clone has to work without a network. The
    price of vendoring is a copy that can quietly stop matching its source -
    four copies of this file exist across the project - so the hash beside it
    is checked before anything else.

    This catches local edits. It cannot tell you the *upstream* file has moved
    on; no offline check can. `./refresh-vectors.sh` is how you find that out.
    """
    if not os.path.exists(FIXTURES_SHA):
        return
    want = open(FIXTURES_SHA).read().split()[0]
    got = hashlib.sha256(open(FIXTURES, "rb").read()).hexdigest()
    if got != want:
        print("FIXTURES DO NOT MATCH THE PINNED HASH", file=sys.stderr)
        print(f"  expected {want}", file=sys.stderr)
        print(f"  found    {got}", file=sys.stderr)
        print("", file=sys.stderr)
        print("rubp-messages-v1.json has been edited since it was pinned.", file=sys.stderr)
        print("These vectors are shared - the canonical copy lives at", file=sys.stderr)
        print("  https://github.com/rachel-multiverse/protocol", file=sys.stderr)
        print("Run ./refresh-vectors.sh to pull it and re-pin, or restore the", file=sys.stderr)
        print("file. Do not edit it here: a client's private idea of the wire", file=sys.stderr)
        print("format is the one bug this harness cannot catch.", file=sys.stderr)
        sys.exit(2)


def main():
    check_fixtures_pinned()
    fixtures = json.load(open(FIXTURES))
    print(f"RUBP codec conformance — Dragon client vs {fixtures['fixture']}\n")
    gen_vectors_inc(fixtures)
    assemble()
    if "--assemble-only" in sys.argv[1:]:
        print("ASSEMBLE ONLY: conformance cartridge built successfully.")
        return
    got = capture()
    failed = check_encoders(fixtures, got)
    failed |= check_decoders(fixtures, got)
    if failed:
        print("RESULT: failures present — see FAIL / [BUG] / [UNEXPECTED] above.")
        sys.exit(1)
    print("RESULT: encoders conformant (platform/name/gaps only); "
          "decoders extract every field correctly.")


if __name__ == "__main__":
    main()
